language: node_js
node_js:
  - "11.7.0"
  - "node"

before_install:
  - npm i -g npm@6.5.0

install:
  - npm ci

branches:
  only:
    - VueConversion
  except:
    - gh-pages
stages:
  - build
jobs:
  include:
    - stage: build
      script:
        - node ./node_modules/vue-gh-pages/index.js -b gh-pages